import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { init, increment, trigger_value, baseAccount, contractAddress, getEvent } from './utils';
import {
  ClientFactory,
  Client,
  DefaultProviderUrls} from "@massalabs/massa-web3";
import React from 'react';
// create a base account for signing transactions


async function createClient() {

  // create a base account for signing transactions
  // initialize a testnet client
  const client = await ClientFactory.createDefaultClient(
    DefaultProviderUrls.TESTNET,
    true,
    baseAccount
  );
  return client;

}

export default function Home() {
  const [client, setClient] = React.useState<Client>();
  const [counter, setCounter] = React.useState<Uint8Array>();
  const [event, setEvent] = React.useState<any>();
  React.useEffect(() => {
    createClient().then((client) => {
      setClient(client);
    });
  }, []);
  React.useEffect(() => {

    if (client) {
      getEvent(client);
    }

  }, [client]);
  console.log(event);



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        {/* button that call init */}
        <button onClick={() => {
          if (client) {
            init(client, contractAddress).then((operationId) => {
              console.log("operationId", operationId);
            });
          }
        }}>init</button>
        {/* button that call increment */}

        <button onClick={() => {
          if (client) {
            increment(client, contractAddress).then((operationId) => {
              console.log("operationId", operationId);
            });
          }
        }}>increment</button>
        {/* button that call trigger_value */}
        <button onClick={() => {
          if (client) {
            trigger_value(client, contractAddress).then((operationId) => {
              console.log("operationId", operationId);
            });
          }
        }}>trigger_value</button>

      </main>
    </>
  );
}
